eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  cloud:
    config:
      label: master
      profile: dev
      uri: http://127.0.0.1:8888/
